<?php

return array(
    "c-date" => array(
        "brandName" => "C-Date",
        "usersOnline" => 8995,
        "hookupRate" => "94",
        "genderRatingMale" => "46",
        "genderRatingFemale" => "54",
        "linkID" => "12345",
    ),
    "ashley-madison" => array(
        "brandName" => "Ashley Madison",
        "usersOnline" => 5675,
        "hookupRate" => "91",
        "genderRatingMale" => "40",
        "genderRatingFemale" => "60",
        "linkID" => "456345",
    ),
    "adultfriendfinder" => array(
        "brandName" => "AdultFriendFinder",
        "usersOnline" => 10234,
        "hookupRate" => "85",
        "genderRatingMale" => "55",
        "genderRatingFemale" => "45",
        "linkID" => "78901",
    ),
    "friend-finder" => array(
        "brandName" => "FriendFinder",
        "usersOnline" => 4321,
        "hookupRate" => "82",
        "genderRatingMale" => "50",
        "genderRatingFemale" => "50",
        "linkID" => "23456",
    ),
    "benaughty" => array(
        "brandName" => "BeNaughty",
        "usersOnline" => 8765,
        "hookupRate" => "90",
        "genderRatingMale" => "60",
        "genderRatingFemale" => "40",
        "linkID" => "34567",
    ),
    "jerkmate" => array(
        "brandName" => "Jerkmate",
        "usersOnline" => 6543,
        "hookupRate" => "88",
        "genderRatingMale" => "70",
        "genderRatingFemale" => "30",
        "linkID" => "45678",
    ),
    "victoriamilan" => array(
        "brandName" => "VictoriaMilan",
        "usersOnline" => 5432,
        "hookupRate" => "84",
        "genderRatingMale" => "65",
        "genderRatingFemale" => "35",
        "linkID" => "56789",
    ),
    "searchingforsingles" => array(
        "brandName" => "SearchingForSingles",
        "usersOnline" => 3210,
        "hookupRate" => "81",
        "genderRatingMale" => "55",
        "genderRatingFemale" => "45",
        "linkID" => "67890",
    ),
);
